---
- name: include rabbitmq installation tasks
  include: "{{ ansible_os_family }}/install.yml"

- include: configure.yml

- include: configure-cluster.yml
  when: rabbitmq_cluster

- name: start rabbitmq server
  service:
    name: rabbitmq-server
    enabled: True
    state: started

- include: vhosts.yml

- include: users.yml

- include: plugins.yml

- include: cluster.yml
  when: rabbitmq_cluster and rabbitmq_nodename != rabbitmq_cluster_master
